name: pull_request
on:
  pull_request

jobs:
  config:
    name: 🛠 🔨 Setup Version
    runs-on: ubuntu-latest
    outputs:
      APP_VERSION: ${{ steps.config.outputs.APP_VERSION }}
    steps:

      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup version
        id: config
        run: |-
          APP_VERSION=$(node -p "require('./package.json').version")
          echo "app_version=$APP_VERSION" >> $GITHUB_OUTPUT
          echo "app_version = $APP_VERSION"

  docker:
    runs-on: ubuntu-latest
    name: 🐋 ☁️ Build Application
    needs: [ config ]
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/app:${{ needs.config.outputs.APP_VERSION }}
