name: Release npm package

on:
  push:
    branches:
      - develop

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with: 
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN_BOT_2}}
        name:
          git config user.name "my-org-bot"
          git config user.email "keysha.journel@gmail.com"
      - uses: actions/setup-node@v1
        with:
          node-version: "20.x"
      - run: npm ci
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}